/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as farmerRegistryInterfaceSol from './FarmerRegistryInterface.sol/index.js';
export * as ix2EarnRewardsPoolSol from './IX2EarnRewardsPool.sol/index.js';
export * as lendingPoolInterfaceSol from './LendingPoolInterface.sol/index.js';
export * as oracleInterfaceSol from './OracleInterface.sol/index.js';
export * as pledgeManagerInterfaceSol from './PledgeManagerInterface.sol/index.js';
export * as rewardsProviderInterfaceSol from './RewardsProviderInterface.sol/index.js';
export * as veFarmersFactoryInterfaceSol from './VeFarmersFactoryInterface.sol/index.js';