/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { RewardsProviderInterface, RewardsProviderInterfaceInterface } from "../../../interfaces/RewardsProviderInterface.sol/RewardsProviderInterface.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "appId",
        "type": "bytes32"
      }
    ],
    "name": "AppIdChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "newRate",
        "type": "uint256"
      }
    ],
    "name": "RateChanged",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "address",
        "name": "newRewardsPool",
        "type": "address"
      }
    ],
    "name": "RewardsPoolChanged",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "appId",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "rate",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "rewardsPool",
    "outputs": [
      {
        "internalType": "contract IX2EarnRewardsPool",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class RewardsProviderInterface__factory {
    static readonly abi = _abi;
    static createInterface(): RewardsProviderInterfaceInterface {
      return new Interface(_abi) as RewardsProviderInterfaceInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): RewardsProviderInterface {
      return new Contract(address, _abi, runner) as unknown as RewardsProviderInterface;
    }
  }
  