/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as farmerRegistrySol from './FarmerRegistry.sol/index.js';
export * as fiatSol from './Fiat.sol/index.js';
export * as lendingPoolSol from './LendingPool.sol/index.js';
export * as oracleSol from './Oracle.sol/index.js';
export * as pledgeManagerSol from './PledgeManager.sol/index.js';
export * as rewardsProviderSol from './RewardsProvider.sol/index.js';
export * as veFarmersFactorySol from './VeFarmersFactory.sol/index.js';
export * as interfaces from './interfaces/index.js';
export * as libs from './libs/index.js';