/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface FarmerRegistryInterface extends Interface {
    getFunction(nameOrSignature: "adminSetFarmer" | "allManagers" | "farmerToManager" | "getAllManagers" | "getManager" | "getProfileUri" | "owner" | "profileUri" | "provider" | "registerFarmer" | "renounceOwnership" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FarmerRegistered" | "FarmerUpdated" | "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'adminSetFarmer', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'allManagers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'farmerToManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getAllManagers', values?: undefined): string;
encodeFunctionData(functionFragment: 'getManager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getProfileUri', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'profileUri', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'provider', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerFarmer', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'adminSetFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allManagers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'farmerToManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllManagers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getProfileUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'profileUri', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'provider', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerFarmer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace FarmerRegisteredEvent {
      export type InputTuple = [farmer: AddressLike, pool: AddressLike, profileUri: string, manager: AddressLike];
      export type OutputTuple = [farmer: string, pool: string, profileUri: string, manager: string];
      export interface OutputObject {farmer: string, pool: string, profileUri: string, manager: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FarmerUpdatedEvent {
      export type InputTuple = [farmer: AddressLike, profileUri: string];
      export type OutputTuple = [farmer: string, profileUri: string];
      export interface OutputObject {farmer: string, profileUri: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FarmerRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): FarmerRegistry;
    waitForDeployment(): Promise<this>;

    interface: FarmerRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    adminSetFarmer: TypedContractMethod<
      [farmer: AddressLike, _profileUri: string, ],
      [void],
      'nonpayable'
    >
    

    
    allManagers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    farmerToManager: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    getAllManagers: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getManager: TypedContractMethod<
      [farmer: AddressLike, ],
      [string],
      'view'
    >
    

    
    getProfileUri: TypedContractMethod<
      [farmer: AddressLike, ],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    profileUri: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    registerFarmer: TypedContractMethod<
      [_profileUri: string, pool: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'adminSetFarmer'): TypedContractMethod<
      [farmer: AddressLike, _profileUri: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allManagers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'farmerToManager'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAllManagers'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getManager'): TypedContractMethod<
      [farmer: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getProfileUri'): TypedContractMethod<
      [farmer: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'profileUri'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'provider'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registerFarmer'): TypedContractMethod<
      [_profileUri: string, pool: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FarmerRegistered'): TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
getEvent(key: 'FarmerUpdated'): TypedContractEvent<FarmerUpdatedEvent.InputTuple, FarmerUpdatedEvent.OutputTuple, FarmerUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'FarmerRegistered(address,address,string,address)': TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
      FarmerRegistered: TypedContractEvent<FarmerRegisteredEvent.InputTuple, FarmerRegisteredEvent.OutputTuple, FarmerRegisteredEvent.OutputObject>;
    

      'FarmerUpdated(address,string)': TypedContractEvent<FarmerUpdatedEvent.InputTuple, FarmerUpdatedEvent.OutputTuple, FarmerUpdatedEvent.OutputObject>;
      FarmerUpdated: TypedContractEvent<FarmerUpdatedEvent.InputTuple, FarmerUpdatedEvent.OutputTuple, FarmerUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }