/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface VeFarmersFactoryInterface extends Interface {
    getFunction(nameOrSignature: "allPools" | "controller" | "createPool" | "fiatToPool" | "oracle" | "owner" | "registry" | "renounceOwnership" | "setConfiguration" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ControllerUpdated" | "OracleUpdated" | "OwnershipTransferred" | "PoolCreated" | "RegistryUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'allPools', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'controller', values?: undefined): string;
encodeFunctionData(functionFragment: 'createPool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'fiatToPool', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setConfiguration', values: [AddressLike, AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'allPools', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'controller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fiatToPool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setConfiguration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ControllerUpdatedEvent {
      export type InputTuple = [newController: AddressLike];
      export type OutputTuple = [newController: string];
      export interface OutputObject {newController: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OracleUpdatedEvent {
      export type InputTuple = [newOracle: AddressLike];
      export type OutputTuple = [newOracle: string];
      export interface OutputObject {newOracle: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PoolCreatedEvent {
      export type InputTuple = [fiat: AddressLike, pool: AddressLike, poolIndex: BigNumberish];
      export type OutputTuple = [fiat: string, pool: string, poolIndex: bigint];
      export interface OutputObject {fiat: string, pool: string, poolIndex: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegistryUpdatedEvent {
      export type InputTuple = [newRegistry: AddressLike];
      export type OutputTuple = [newRegistry: string];
      export interface OutputObject {newRegistry: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VeFarmersFactory extends BaseContract {
    
    connect(runner?: ContractRunner | null): VeFarmersFactory;
    waitForDeployment(): Promise<this>;

    interface: VeFarmersFactoryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allPools: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    controller: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    createPool: TypedContractMethod<
      [fiat: AddressLike, ],
      [string],
      'nonpayable'
    >
    

    
    fiatToPool: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setConfiguration: TypedContractMethod<
      [_controller: AddressLike, _oracle: AddressLike, _registry: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allPools'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'controller'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createPool'): TypedContractMethod<
      [fiat: AddressLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fiatToPool'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setConfiguration'): TypedContractMethod<
      [_controller: AddressLike, _oracle: AddressLike, _registry: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ControllerUpdated'): TypedContractEvent<ControllerUpdatedEvent.InputTuple, ControllerUpdatedEvent.OutputTuple, ControllerUpdatedEvent.OutputObject>;
getEvent(key: 'OracleUpdated'): TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PoolCreated'): TypedContractEvent<PoolCreatedEvent.InputTuple, PoolCreatedEvent.OutputTuple, PoolCreatedEvent.OutputObject>;
getEvent(key: 'RegistryUpdated'): TypedContractEvent<RegistryUpdatedEvent.InputTuple, RegistryUpdatedEvent.OutputTuple, RegistryUpdatedEvent.OutputObject>;

    filters: {
      
      'ControllerUpdated(address)': TypedContractEvent<ControllerUpdatedEvent.InputTuple, ControllerUpdatedEvent.OutputTuple, ControllerUpdatedEvent.OutputObject>;
      ControllerUpdated: TypedContractEvent<ControllerUpdatedEvent.InputTuple, ControllerUpdatedEvent.OutputTuple, ControllerUpdatedEvent.OutputObject>;
    

      'OracleUpdated(address)': TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
      OracleUpdated: TypedContractEvent<OracleUpdatedEvent.InputTuple, OracleUpdatedEvent.OutputTuple, OracleUpdatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PoolCreated(address,address,uint256)': TypedContractEvent<PoolCreatedEvent.InputTuple, PoolCreatedEvent.OutputTuple, PoolCreatedEvent.OutputObject>;
      PoolCreated: TypedContractEvent<PoolCreatedEvent.InputTuple, PoolCreatedEvent.OutputTuple, PoolCreatedEvent.OutputObject>;
    

      'RegistryUpdated(address)': TypedContractEvent<RegistryUpdatedEvent.InputTuple, RegistryUpdatedEvent.OutputTuple, RegistryUpdatedEvent.OutputObject>;
      RegistryUpdated: TypedContractEvent<RegistryUpdatedEvent.InputTuple, RegistryUpdatedEvent.OutputTuple, RegistryUpdatedEvent.OutputObject>;
    
    };
  }