/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interestLibSol from './InterestLib.sol/index.js';
export type { interestLibSol };
import type * as lendingPoolLogicSol from './LendingPoolLogic.sol/index.js';
export type { lendingPoolLogicSol };