/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IX2EarnRewardsPool, IX2EarnRewardsPoolInterface } from "../../../interfaces/IX2EarnRewardsPool.sol/IX2EarnRewardsPool.js";

  const _abi = [
  {
    "inputs": [],
    "name": "InsufficientAmount",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "appId",
        "type": "bytes32"
      }
    ],
    "name": "availableFunds",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "appId",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      },
      {
        "internalType": "string",
        "name": "proof",
        "type": "string"
      }
    ],
    "name": "distributeReward",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IX2EarnRewardsPool__factory {
    static readonly abi = _abi;
    static createInterface(): IX2EarnRewardsPoolInterface {
      return new Interface(_abi) as IX2EarnRewardsPoolInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IX2EarnRewardsPool {
      return new Contract(address, _abi, runner) as unknown as IX2EarnRewardsPool;
    }
  }
  