/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as farmerRegistryInterfaceSol from './FarmerRegistryInterface.sol/index.js';
export type { farmerRegistryInterfaceSol };
import type * as ix2EarnRewardsPoolSol from './IX2EarnRewardsPool.sol/index.js';
export type { ix2EarnRewardsPoolSol };
import type * as lendingPoolInterfaceSol from './LendingPoolInterface.sol/index.js';
export type { lendingPoolInterfaceSol };
import type * as oracleInterfaceSol from './OracleInterface.sol/index.js';
export type { oracleInterfaceSol };
import type * as pledgeManagerInterfaceSol from './PledgeManagerInterface.sol/index.js';
export type { pledgeManagerInterfaceSol };
import type * as rewardsProviderInterfaceSol from './RewardsProviderInterface.sol/index.js';
export type { rewardsProviderInterfaceSol };
import type * as veFarmersFactoryInterfaceSol from './VeFarmersFactoryInterface.sol/index.js';
export type { veFarmersFactoryInterfaceSol };