/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface IX2EarnRewardsPoolInterface extends Interface {
    getFunction(nameOrSignature: "availableFunds" | "distributeReward"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'availableFunds', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'distributeReward', values: [BytesLike, BigNumberish, AddressLike, string]): string;

    decodeFunctionResult(functionFragment: 'availableFunds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeReward', data: BytesLike): Result;
  }

  

  export interface IX2EarnRewardsPool extends BaseContract {
    
    connect(runner?: ContractRunner | null): IX2EarnRewardsPool;
    waitForDeployment(): Promise<this>;

    interface: IX2EarnRewardsPoolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    availableFunds: TypedContractMethod<
      [appId: BytesLike, ],
      [bigint],
      'view'
    >
    

    
    distributeReward: TypedContractMethod<
      [appId: BytesLike, amount: BigNumberish, receiver: AddressLike, proof: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'availableFunds'): TypedContractMethod<
      [appId: BytesLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'distributeReward'): TypedContractMethod<
      [appId: BytesLike, amount: BigNumberish, receiver: AddressLike, proof: string, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }