/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { FarmerRegistryInterface, FarmerRegistryInterfaceInterface } from "../../../interfaces/FarmerRegistryInterface.sol/FarmerRegistryInterface.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "farmer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "pool",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "profileUri",
        "type": "string"
      },
      {
        "indexed": false,
        "internalType": "address",
        "name": "manager",
        "type": "address"
      }
    ],
    "name": "FarmerRegistered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "farmer",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "string",
        "name": "profileUri",
        "type": "string"
      }
    ],
    "name": "FarmerUpdated",
    "type": "event"
  },
  {
    "inputs": [],
    "name": "getAllManagers",
    "outputs": [
      {
        "internalType": "address[]",
        "name": "",
        "type": "address[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "farmer",
        "type": "address"
      }
    ],
    "name": "getManager",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "farmer",
        "type": "address"
      }
    ],
    "name": "getProfileUri",
    "outputs": [
      {
        "internalType": "string",
        "name": "",
        "type": "string"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class FarmerRegistryInterface__factory {
    static readonly abi = _abi;
    static createInterface(): FarmerRegistryInterfaceInterface {
      return new Interface(_abi) as FarmerRegistryInterfaceInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): FarmerRegistryInterface {
      return new Contract(address, _abi, runner) as unknown as FarmerRegistryInterface;
    }
  }
  